=== litebin/webUI/webdriver1/config/TestData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="method">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="parameters" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="parameter" type="xs:string" minOccurs="0"
								maxOccurs="unbounded" />
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== litebin/webUI/webdriver1/data/TestData.xml
<?xml version="1.0" encoding="UTF-8"?>
<method name="testMethod" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../config/TestData.xsd">
	<parameters name="group1">
		<parameter>0</parameter>
		<parameter>1</parameter>
		<parameter>1</parameter>
	</parameters>
	<parameters name="group2">
		<parameter>1</parameter>
		<parameter>2</parameter>
		<parameter>3</parameter>
	</parameters>
	<parameters name="group23">
		<parameter>11</parameter>
		<parameter>22</parameter>
		<parameter>33</parameter>
	</parameters>	
</method>
